-- Place SQL statements that are used to initialize the database schema
-- within this file. Subsequent schema migrations should be placed within
-- a n.up.sql file, where n increments a sequence number beginning with 1.